#!/usr/bin/env -S bash -Eeuxo pipefail

# compile - Autobuild Bash script for UNIX.
# Copyright (C) 2023  Makonede
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


TID=01007EF00011E000
RELEASE_PATH=release/atmosphere/contents/$TID

python3 -m pip install -U pip
python3 -m pip install -U setuptools
python3 -m pip install -U wheel
python3 -m pip install -Ur tools/botw-link/requirements.txt
python3 -m pip install -U vidua
rm -rf build/*
python3 tools/botw-link config/botw-link.toml -cvV 160
rm -rf patched/ release/
mkdir -p $RELEASE_PATH/exefs
cp -Rf build/LinkCannon.nso $RELEASE_PATH/exefs/subsdk9
cp -Rf build/app.npdm $RELEASE_PATH/exefs/main.npdm
cp -Rf romfs/ $RELEASE_PATH/
python3 patch.py
cp -Rf patched/* $RELEASE_PATH/romfs

set +x
echo
echo Build complete. To install, copy the contents of the release folder onto the
echo root of your microSD card.
read -n1 -r -p "Press any key to continue..."
