#!/usr/bin/env -S bash -Eeuxo pipefail

VERSION=0.1
TID=01007EF00011E000
BID=8E9978D50BDD20B4
RELEASE_PATH=release/atmosphere/contents/$TID

make -C build -f ../Makefile
rm -rf release/
mkdir -p $RELEASE_PATH/exefs
mkdir -p $RELEASE_PATH/romfs/System
mkdir -p $RELEASE_PATH/cheats
echo 1.6.0-LC$VERSION > $RELEASE_PATH/romfs/System/Version.txt
cp -Rf build/linkcannon.nso $RELEASE_PATH/exefs/subsdk9
cp -Rf build/app.npdm $RELEASE_PATH/exefs/main.npdm
cp -Rf romfs/ $RELEASE_PATH/
cp -Rf cheat.txt $RELEASE_PATH/cheats/$BID.txt

set +x
echo
echo Build complete. To install, copy the contents of the release folder onto the
echo root of your microSD card.
