#!/usr/bin/env -S bash -Eeuxo pipefail

# setup_build - Build setup Bash script for UNIX.
# Copyright (C) 2023  Makonede
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


mkdir -p dump/Pack dump/System/Resource

[ -d .venv ] || python3 -m venv .venv
. .venv/bin/activate
python3 -m pip install -U pip
python3 -m pip install -U wheel
python3 -m pip install -U setuptools
python3 -m pip install -Ur tools/botw-link/requirements.txt
python3 -m pip install -U vidua
