#!/usr/bin/env -S bash -Eeuxo pipefail

# setup_build - Build setup Bash script for UNIX.
# Copyright (C) 2023  Makonede
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


mkdir -p dump/Pack dump/System/Resource
rm -rf gcm.cache/*

$DEVKITPRO/aarch64-none-elf-g++ -c -fmodules-ts -x c++-system-header \
  -std=gnu++2b algorithm any array atomic barrier bit bitset cassert cctype \
  cerrno cfenv cfloat charconv chrono cinttypes climits clocale cmath compare \
  complex concepts condition_variable coroutine csetjmp csignal cstdarg \
  cstddef cstdint cstdio cstdlib cstring ctime cuchar cwchar cwctype deque \
  exception execution expected filesystem flat_map flat_set format \
  forward_list fstream functional future generator hazard_pointer \
  initializer_list iomanip ios iosfwd iostream istream iterator latch limits \
  list locale map mdspan memory memory_resource mutex new numbers numeric \
  optional ostream print queue random ranges ratio rcu regex scoped_allocator \
  semaphore set shared_mutex source_location span spanstream sstream stack \
  stacktrace stdexcept stdfloat stop_token streambuf string string_view \
  syncstream system_error text_encoding thread tuple type_traits typeindex \
  typeinfo unordered_map unordered_set utility valarray variant vector version \
  || true

[ -d .venv ] || python3 -m venv .venv
. .venv/bin/activate
python3 -m pip install -U pip
python3 -m pip install -U wheel
python3 -m pip install -U setuptools
python3 -m pip install -Ur tools/botw-link/requirements.txt
python3 -m pip install -U vidua
