#!/usr/bin/env -S bash -Eeuxo pipefail

# deploy - UKMM autodeploy Bash script for UNIX.
# Copyright (C) 2023  Makonede
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


CMAKE_VERSION=3.25.2

if ! hash rustc 2> /dev/null; then
  curl -fSs https://sh.rustup.rs | sh -s -- -y --default-host x86_64-unknown-linux-gnu --default-toolchain nightly --profile complete
fi

if ! hash cmake 2> /dev/null; then
  curl -fLSs https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-linux-x86_64.sh | sh -s -- --skip-license
fi

. ~/.profile
cd ukmm
cargo build --release
